version: "3"

services:
  db:
    image: "mysql"
    container_name: "sw_db"
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "watch"
    volumes:
      - "sw_data:/var/lib/mysql"
      - ./schema.sql:/docker-entrypoint-initdb.d/init.sql

  phpmyadmin:
    image: "phpmyadmin/phpmyadmin"
    container_name: "sw_phpmyadmin"
    ports:
      - "8080:80"
    volumes:
      - "/sessions"

volumes:
  sw_data: ~
