version: "3"

services:
  db:
    image: "mariadb"
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "watch"
    volumes:
      - "data:/var/lib/mysql"
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql

  phpmyadmin:
    image: "phpmyadmin/phpmyadmin"
    ports:
      - "8080:80"
    volumes:
      - "/sessions"

volumes:
  data: ~
